name = "mock-moving-avg"
version = "0.1.0"
builder = "builder.py"
calendar = "NYSE"
granularity = "1d"
start-date = "2020-01-01"

[schema]
ticker = "str"
average = "float"

[dependencies]
mock-daily-close = {version = "0.1.0", lookback = "5d"}
