repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        files: ^builders/
      - id: ruff-format
        args: [--check]
        files: ^builders/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^builders/server/
        exclude: ^builders/server/tests/
        args: [--config-file=pyproject.toml, builders/server]
        pass_filenames: false
        additional_dependencies:
          - pandas-stubs
          - types-requests
          - types-psycopg2

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.0.4
    hooks:
      - id: sqlfluff-lint

  - repo: local
    hooks:
      - id: no-absolute-paths
        name: check for absolute paths
        language: pygrep
        entry: '/(?:Users|home)/[a-zA-Z0-9_.-]+|[A-Z]:\\[A-Za-z]'

      - id: pytest
        name: pytest
        entry: bash -c 'uv run pytest --ignore=builders/server/tests/integration'
        language: system
        files: ^builders/server/
        pass_filenames: false
